CONFIG_ENABLE_NET=y
CONFIG_ENABLE_VFS=y
CONFIG_KERNEL_ASYNC=y
CONFIG_MAIN_THREAD_STACK_SIZE=32768
CONFIG_NET_ROUTER_IP="10.171.198.28"
CONFIG_NET_STATIC_IP="10.171.198.245"
# CONFIG_NET_STATIC_IP="10.171.198.246" true
CONFIG_ENABLE_WLAN=y
# Change the following two lines to your Wi-Fi SSID and password.
CONFIG_WLAN_SSID="bluekernel1"
CONFIG_WLAN_PASSWORD="12345678"
CONFIG_GPIO=y
CONFIG_I2C_CORE=y
CONFIG_BME280=y
CONFIG_SPI_CORE=y
CONFIG_MAX7219=y
CONFIG_USB_SERIAL=y
CONFIG_ST7796=y
CONFIG_LCD=y
